# Generated by Django 5.1.4 on 2024-12-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightcg', '0002_lutador_descricao_lutador_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='luta',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='lutas/'),
        ),
    ]
